export function createMergerTutorialDefinition(context = {}) {
  const {
    TAB_MERGER,
    createModuleTutorialStep,
    withSection,
    mergerFrameTarget,
    openMergerToolForTutorial,
  } = context;
  return [
    ...withSection('Werkzeuge', [
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'Werkzeugauswahl',
        copy: 'Wechsle zwischen Layout, Zusammenführen, Drehen und Aufteilen. Jedes Werkzeug arbeitet für sich; deine Originaldateien bleiben unverändert.',
        target: mergerFrameTarget('.tool-tab-bar'),
        placement: 'bottom',
        beforeRender: () => openMergerToolForTutorial('layout'),
      }),
    ]),
    ...withSection('Seiten aufs Blatt', [
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'Seiten auf ein Blatt',
        copy: 'Dieses Werkzeug ordnet mehrere PDF-Seiten verkleinert auf einem gemeinsamen Blatt an – gut geeignet, um Kopierkosten zu sparen.',
        target: mergerFrameTarget(['#tool-panel-layout .panel-head', '#tool-panel-layout']),
        placement: 'bottom',
        beforeRender: () => openMergerToolForTutorial('layout'),
      }),
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'PDF auswählen',
        copy: 'Ziehe eine PDF hierher oder klicke zur Dateiauswahl. Die Datei wird nur im Browser verarbeitet und nicht hochgeladen.',
        target: mergerFrameTarget('#layoutDropZone'),
        placement: 'top',
        beforeRender: () => openMergerToolForTutorial('layout'),
      }),
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'Seiten pro Blatt',
        copy: 'Lege fest, ob zwei, vier, sechs oder acht Ausgangsseiten auf einem Blatt landen. Je mehr Seiten, desto kleiner die Darstellung.',
        target: mergerFrameTarget('#pagesButtons'),
        placement: 'right',
        beforeRender: () => openMergerToolForTutorial('layout'),
      }),
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'Spezialmodus für drei Seiten',
        copy: 'Bei drei Seiten entsteht eine doppelte Startseite plus ein Blatt für Seite zwei und drei. So passt ein dreiseitiges Arbeitsblatt auf zwei beidseitig bedruckte Blätter.',
        target: mergerFrameTarget('#specialThreeModeButton'),
        placement: 'right',
        beforeRender: () => openMergerToolForTutorial('layout'),
      }),
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'Ausrichtung optimieren',
        copy: 'Diese Option wählt automatisch Hoch- oder Querformat, damit die Seiten möglichst groß auf das Blatt passen.',
        target: mergerFrameTarget('#autoOrientationToggle'),
        placement: 'right',
        beforeRender: () => openMergerToolForTutorial('layout'),
      }),
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'Kopien passend zur Lerngruppe',
        copy: 'Trage die Anzahl der Lernenden ein. Restseiten werden dann so gefüllt, dass genau genug Kopien für die Gruppe entstehen.',
        target: mergerFrameTarget('#studentCount'),
        placement: 'right',
        beforeRender: () => openMergerToolForTutorial('layout'),
      }),
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'Restseiten',
        copy: 'Entscheide, ob freie Plätze auf dem letzten Blatt leer bleiben oder mit vorhandenen Seiten aufgefüllt werden.',
        target: mergerFrameTarget('#layoutPaddingModeGroup'),
        placement: 'right',
        beforeRender: () => openMergerToolForTutorial('layout'),
      }),
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'Layout erstellen',
        copy: 'Dieser Button erzeugt die neue PDF. Sobald sie fertig ist, meldet sich ein Hinweisfenster, aus dem du sie öffnen kannst.',
        target: mergerFrameTarget('#layoutStartButton'),
        placement: 'top',
        beforeRender: () => openMergerToolForTutorial('layout'),
      }),
    ]),
    ...withSection('Zusammenführen', [
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'Dateien verbinden',
        copy: 'Lade mehrere PDFs gleichzeitig oder nacheinander. Sie werden zu einer einzigen Datei verbunden.',
        target: mergerFrameTarget('#mergeDropZone'),
        placement: 'top',
        beforeRender: () => openMergerToolForTutorial('merge'),
      }),
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'Dateireihenfolge',
        copy: 'Nach dem Laden erscheint hier die Dateiliste. Per Drag-and-drop legst du die Reihenfolge fest; weitere PDFs lassen sich ergänzen oder entfernen.',
        target: mergerFrameTarget(['#mergeFileListShell:not(.hidden)', '#mergeAppendFileList:not(:empty)', '#mergeDropZone']),
        placement: 'top',
        beforeRender: () => openMergerToolForTutorial('merge'),
      }),
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'Gesamtseitenanzahl prüfen',
        copy: 'Unter der Liste steht, wie viele Seiten das Ergebnis haben wird. Eine gerade Zahl ist praktisch für beidseitigen Druck.',
        target: mergerFrameTarget(['#mergeTotalPages', '#mergeDropZone']),
        placement: 'top',
        beforeRender: () => openMergerToolForTutorial('merge'),
      }),
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'Dateien zusammenführen',
        copy: 'Dieser Button verbindet alle geladenen PDFs in der angezeigten Reihenfolge zu einer neuen Datei.',
        target: mergerFrameTarget('#mergeStartButton'),
        placement: 'top',
        beforeRender: () => openMergerToolForTutorial('merge'),
      }),
    ]),
    ...withSection('Drehen', [
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'PDF drehen',
        copy: 'Wähle hier die PDF aus, deren Seiten falsch herum liegen – etwa nach einem Scan im Querformat.',
        target: mergerFrameTarget('#rotateDropZone'),
        placement: 'top',
        beforeRender: () => openMergerToolForTutorial('rotate'),
      }),
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'Ganzes Dokument drehen',
        copy: 'Wende eine Drehung von 90, 180 oder 270 Grad einheitlich auf alle Seiten an.',
        target: mergerFrameTarget('#rotateDocumentDegreesGroup'),
        placement: 'right',
        beforeRender: () => openMergerToolForTutorial('rotate'),
      }),
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'Einzelne Seiten drehen',
        copy: 'Nach dem Laden erscheinen hier die Seitenvorschauen. Die Drehschaltflächen gelten jeweils nur für die ausgewählte Seite.',
        target: mergerFrameTarget(['.rotate-page-card', '#rotatePagesList:not(:empty)', '#rotateDropZone']),
        placement: 'top',
        beforeRender: () => openMergerToolForTutorial('rotate'),
      }),
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'Gedrehte PDF erstellen',
        copy: 'Dieser Button erzeugt eine neue PDF mit den festgelegten Drehungen. Die Ausgangsdatei bleibt unverändert.',
        target: mergerFrameTarget('#rotateStartButton'),
        placement: 'top',
        beforeRender: () => openMergerToolForTutorial('rotate'),
      }),
    ]),
    ...withSection('Aufteilen', [
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'PDF aufteilen',
        copy: 'Lade die PDF, aus der du einzelne Seiten oder Seitengruppen herauslösen möchtest.',
        target: mergerFrameTarget('#splitDropZone'),
        placement: 'top',
        beforeRender: () => openMergerToolForTutorial('split'),
      }),
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'Seitenauswahl',
        copy: 'Nach dem Laden erscheinen hier alle Seiten. Ein Klick auf eine Seite nimmt sie in die Ausgabe auf oder schließt sie aus.',
        target: mergerFrameTarget([
          '.split-page-card',
          '#splitPagesList:not(:empty)',
          '.split-toolbar-group-selection',
          '#splitDropZone',
        ]),
        placement: 'top',
        beforeRender: () => openMergerToolForTutorial('split'),
      }),
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'Alle Seiten auf einmal',
        copy: 'Mit diesen beiden Knöpfen wählst du alle Seiten gleichzeitig aus oder ab – praktisch, wenn du nur wenige Seiten brauchst.',
        target: mergerFrameTarget(['#splitActivateAllButton', '.split-toolbar-group-selection']),
        placement: 'right',
        beforeRender: () => openMergerToolForTutorial('split'),
      }),
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'Ausgabeformat',
        copy: 'Lege fest, ob die ausgewählten Seiten gemeinsam in einer PDF landen oder als einzelne Dateien ausgegeben werden.',
        target: mergerFrameTarget('#splitOutputModeGroup'),
        placement: 'right',
        beforeRender: () => openMergerToolForTutorial('split'),
      }),
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'Seitengruppen',
        copy: 'Im Gruppenmodus bildest du Seitenbereiche. Geladene Seiten lassen sich per Drag-and-drop einer anderen Gruppe zuordnen.',
        target: mergerFrameTarget(['#splitGroupRowsList:not(:empty)', '.split-toolbar-group-config', '#splitOutputModeGroup']),
        placement: 'top',
        beforeRender: () => openMergerToolForTutorial('split'),
      }),
      createModuleTutorialStep({
        tab: TAB_MERGER,
        title: 'Aufteilung starten',
        copy: 'Dieser Button erstellt die gewählte gemeinsame oder einzelne Ausgabe. Mehrere Dateien kommen dabei als ZIP.',
        target: mergerFrameTarget('#splitStartButton'),
        placement: 'top',
        beforeRender: () => openMergerToolForTutorial('split'),
      }),
    ]),
  ];
}
